### ISSUE TITLE
Provide a values.yaml

### ISSUE THREAD

**Issue by JasonShin** [gnu-gnu/vbox_vagrant_kubernetes#1]
Thanks for a great project, this is inspiring.

Would you be willing to provide a values.yaml that lays out all the required parameters that end users can easily configure and override upon their need?

This is following the Helm chart convention and it will make this project a bit more comprehensible. 

Please let me know what you think,
Cheers

**Comment by JasonShin** [comment]
No replies and no love

**Comment by gnu-gnu** [comment]
Thanks for your suggestion, I read it all carefully, I will try to provide Helm projects ASAP

**Comment by JasonShin** [comment]
No rush Gnu, love you.
